export interface GeneratedContent {
  title: string;
  body: string;
  image: string;
}

const PLACEHOLDER_IMAGES = [
  'https://upload.wikimedia.org/wikipedia/commons/b/bf/IMac_M4_2024_2_%28cropped%29.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Apple_logo_grey.svg/505px-Apple_logo_grey.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/488px-Apple_logo_black.svg.png',
];

export async function generateContent(query: string): Promise<GeneratedContent> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 5000));

  // Return mock data based on query
  return {
    title: `Response to: ${query}`,
    body: `This is a placeholder response to your query: "${query}"\n\nIn a real implementation, this would be generated by an AI model that provides detailed, contextual information based on your question.\n\nThe content would be relevant, informative, and help you explore the topic further.`,
    image: PLACEHOLDER_IMAGES[Math.floor(Math.random() * PLACEHOLDER_IMAGES.length)],
  };
}
